stages:
  - build
  - test
  - lint

# jobs
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t apply-app-image .

test:
  stage: test
  image: node:lts
  services:
    - name: postgres:13-alpine
      alias: db
  variables:
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
    POSTGRES_USER: apply
    POSTGRES_PASSWORD: apply
    POSTGRES_DB: apply
  script:
    - npm install
    - npm run test

lint:
  stage: lint
  image: node:lts
  services:
    - name: postgres:13-alpine
      alias: db
  variables:
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
    POSTGRES_USER: apply
    POSTGRES_PASSWORD: apply
    POSTGRES_DB: apply
  script:
    - npm install
    - npm run lint
