version: '3'

services:
  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: apply
      POSTGRES_PASSWORD: apply
      POSTGRES_DB: apply
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: apply
      POSTGRES_PASSWORD: apply
      POSTGRES_DB: apply
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
